### ISSUE TITLE
[Bug]: `@Filter()` 注解会在没有参数时抛出异常

### ISSUE THREAD

**Issue by Qubik65536** [zly2006/KhlKt#8]
### 请选择：

- [ ] 我正在着手修复这个问题

### 问题描述

```Markdown
当我在使用 `@Filter()` 注解且不带参数时，会出现 `java.lang.ArrayIndexOutOfBoundsException` 异常。但是实际上，这个注解是有无参数使用的需求的，所以应该解决这个问题。
```

### 重现

```Markdown
1. 向 client 增加下方代码中的 `StatusController` 作为一个监听类
2. 启动 bot
3. 向频道发送 `!!ping`
4. 出现下方日志错误
```

### 相关日志输出（如果有）

```Shell
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1
	at io.github.kookybot.events.EventManager.callEventRaw(EventManager.kt:3034)
	at io.github.kookybot.client.Client$initWebsocket$1.onMessage(Client.kt:554)
	at io.github.kookybot.client.Client$initWebsocket$1.onMessage(Client.kt:541)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:641)
	at org.java_websocket.drafts.Draft_6455.processFrameBinary(Draft_6455.java:959)
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:912)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:401)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:516)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### 相关 Kotlin 代码（如果有）

```Kotlin
class StatusController: Listener {
    @EventHandler
    @Filter("!!ping")
    fun ping(source: CommandSource) {
        source.sendMessage("pong")
    }
}
```

### 环境

```Markdown
- **操作系统**：macOS Monterey 12.4
- **Java 版本：**：Temurin-17.0.1+12
- **KookyBot 版本 (或 commit 号)：**：0.2.1
```

### 请确认以下条款

- [X] 我已经查看了[已有 issue](https://github.com/KookyBot/KookyBot/issues) 并确定我提交的问题并没有重复
- [X] 本 issue 是 bug 反馈
- [X] 本 bug 在最新版本中仍存在

**Comment by zly2006** [comment]
请测试这个bug在最新commit中是否出现？

**Comment by Qubik65536** [comment]
更换新的 project 测试后确定没有问题了，可能是旧 project 依赖管理问题导致测试不准确
